#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  sym_literal_text = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_RBRACE_RBRACE = 3,
  sym_identifier = 4,
  anon_sym_POUND = 5,
  anon_sym_SLASH = 6,
  anon_sym_STAR = 7,
  anon_sym_GT = 8,
  sym_source_file = 9,
  sym__content = 10,
  sym__handlebars = 11,
  sym__expression = 12,
  sym_helper_call = 13,
  sym__block_start = 14,
  sym__block_end = 15,
  sym_handleblock = 16,
  sym__macro_start = 17,
  sym_macro = 18,
  sym__partial_start = 19,
  sym_partial = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_helper_call_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_literal_text] = "literal_text",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_identifier] = "identifier",
  [anon_sym_POUND] = "#",
  [anon_sym_SLASH] = "/block",
  [anon_sym_STAR] = "*",
  [anon_sym_GT] = ">",
  [sym_source_file] = "source_file",
  [sym__content] = "_content",
  [sym__handlebars] = "_handlebars",
  [sym__expression] = "_expression",
  [sym_helper_call] = "helper_call",
  [sym__block_start] = "_block_start",
  [sym__block_end] = "_block_end",
  [sym_handleblock] = "handleblock",
  [sym__macro_start] = "_macro_start",
  [sym_macro] = "macro",
  [sym__partial_start] = "_partial_start",
  [sym_partial] = "partial",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_helper_call_repeat1] = "helper_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_literal_text] = sym_literal_text,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_GT] = anon_sym_GT,
  [sym_source_file] = sym_source_file,
  [sym__content] = sym__content,
  [sym__handlebars] = sym__handlebars,
  [sym__expression] = sym__expression,
  [sym_helper_call] = sym_helper_call,
  [sym__block_start] = sym__block_start,
  [sym__block_end] = sym__block_end,
  [sym_handleblock] = sym_handleblock,
  [sym__macro_start] = sym__macro_start,
  [sym_macro] = sym_macro,
  [sym__partial_start] = sym__partial_start,
  [sym_partial] = sym_partial,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_helper_call_repeat1] = aux_sym_helper_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym__handlebars] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_helper_call] = {
    .visible = true,
    .named = true,
  },
  [sym__block_start] = {
    .visible = false,
    .named = true,
  },
  [sym__block_end] = {
    .visible = false,
    .named = true,
  },
  [sym_handleblock] = {
    .visible = true,
    .named = true,
  },
  [sym__macro_start] = {
    .visible = false,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym__partial_start] = {
    .visible = false,
    .named = true,
  },
  [sym_partial] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_helper_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_helper = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_helper] = "block_helper",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_block_helper, 0, .inherited = true},
  [1] =
    {field_block_helper, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = anon_sym_SLASH,
    [2] = anon_sym_SLASH,
    [3] = anon_sym_SLASH,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 5,
  [13] = 11,
  [14] = 10,
  [15] = 6,
  [16] = 9,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 30,
  [38] = 31,
  [39] = 25,
  [40] = 33,
  [41] = 28,
  [42] = 24,
  [43] = 29,
  [44] = 32,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 48,
  [54] = 49,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '>') ADVANCE(13);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == '}') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '{') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == '}') ADVANCE(8);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '{') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_literal_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_literal_text);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(45),
    [sym__content] = STATE(7),
    [sym__handlebars] = STATE(7),
    [sym__block_start] = STATE(4),
    [sym_handleblock] = STATE(7),
    [sym__macro_start] = STATE(5),
    [sym_macro] = STATE(7),
    [sym__partial_start] = STATE(6),
    [sym_partial] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_literal_text] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
  },
  [2] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(42),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
  [3] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(24),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [4] = {
    [sym__content] = STATE(14),
    [sym__handlebars] = STATE(14),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(30),
    [sym_handleblock] = STATE(14),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(14),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [sym_literal_text] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [5] = {
    [sym__content] = STATE(3),
    [sym__handlebars] = STATE(3),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(31),
    [sym_handleblock] = STATE(3),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(3),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_literal_text] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [6] = {
    [sym__content] = STATE(11),
    [sym__handlebars] = STATE(11),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(25),
    [sym_handleblock] = STATE(11),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(11),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_literal_text] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [7] = {
    [sym__content] = STATE(9),
    [sym__handlebars] = STATE(9),
    [sym__block_start] = STATE(4),
    [sym_handleblock] = STATE(9),
    [sym__macro_start] = STATE(5),
    [sym_macro] = STATE(9),
    [sym__partial_start] = STATE(6),
    [sym_partial] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_literal_text] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
  },
  [8] = {
    [sym__content] = STATE(10),
    [sym__handlebars] = STATE(10),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(37),
    [sym_handleblock] = STATE(10),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(10),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_literal_text] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
  [9] = {
    [sym__content] = STATE(9),
    [sym__handlebars] = STATE(9),
    [sym__block_start] = STATE(4),
    [sym_handleblock] = STATE(9),
    [sym__macro_start] = STATE(5),
    [sym_macro] = STATE(9),
    [sym__partial_start] = STATE(6),
    [sym_partial] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_literal_text] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(30),
  },
  [10] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(41),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
  [11] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(29),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [12] = {
    [sym__content] = STATE(2),
    [sym__handlebars] = STATE(2),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(38),
    [sym_handleblock] = STATE(2),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(2),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_literal_text] = ACTIONS(33),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
  [13] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(43),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
  [14] = {
    [sym__content] = STATE(16),
    [sym__handlebars] = STATE(16),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(28),
    [sym_handleblock] = STATE(16),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(16),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_literal_text] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
  },
  [15] = {
    [sym__content] = STATE(13),
    [sym__handlebars] = STATE(13),
    [sym__block_start] = STATE(8),
    [sym__block_end] = STATE(39),
    [sym_handleblock] = STATE(13),
    [sym__macro_start] = STATE(12),
    [sym_macro] = STATE(13),
    [sym__partial_start] = STATE(15),
    [sym_partial] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [sym_literal_text] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(37), 1,
      sym_literal_text,
    ACTIONS(40), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(8), 1,
      sym__block_start,
    STATE(12), 1,
      sym__macro_start,
    STATE(15), 1,
      sym__partial_start,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [24] = 7,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_SLASH,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(48), 2,
      sym__expression,
      sym_helper_call,
  [47] = 7,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(53), 1,
      anon_sym_SLASH,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(48), 2,
      sym__expression,
      sym_helper_call,
  [70] = 6,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(53), 2,
      sym__expression,
      sym_helper_call,
  [90] = 6,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(48), 2,
      sym__expression,
      sym_helper_call,
  [110] = 3,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(46), 2,
      sym__expression,
      sym_helper_call,
  [121] = 3,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(47), 2,
      sym__expression,
      sym_helper_call,
  [132] = 3,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_helper_call_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_helper_call,
  [143] = 2,
    ACTIONS(57), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [151] = 2,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [159] = 3,
    ACTIONS(63), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(26), 1,
      aux_sym_helper_call_repeat1,
  [169] = 3,
    ACTIONS(68), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(26), 1,
      aux_sym_helper_call_repeat1,
  [179] = 2,
    ACTIONS(74), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [187] = 2,
    ACTIONS(78), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [195] = 2,
    ACTIONS(82), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [203] = 2,
    ACTIONS(86), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [211] = 2,
    ACTIONS(90), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [219] = 2,
    ACTIONS(94), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [227] = 2,
    ACTIONS(96), 1,
      sym_literal_text,
    ACTIONS(98), 1,
      anon_sym_LBRACE_LBRACE,
  [234] = 2,
    ACTIONS(100), 1,
      sym_literal_text,
    ACTIONS(102), 1,
      anon_sym_LBRACE_LBRACE,
  [241] = 2,
    ACTIONS(104), 1,
      sym_literal_text,
    ACTIONS(106), 1,
      anon_sym_LBRACE_LBRACE,
  [248] = 2,
    ACTIONS(80), 1,
      sym_literal_text,
    ACTIONS(82), 1,
      anon_sym_LBRACE_LBRACE,
  [255] = 2,
    ACTIONS(84), 1,
      sym_literal_text,
    ACTIONS(86), 1,
      anon_sym_LBRACE_LBRACE,
  [262] = 2,
    ACTIONS(59), 1,
      sym_literal_text,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
  [269] = 2,
    ACTIONS(92), 1,
      sym_literal_text,
    ACTIONS(94), 1,
      anon_sym_LBRACE_LBRACE,
  [276] = 2,
    ACTIONS(72), 1,
      sym_literal_text,
    ACTIONS(74), 1,
      anon_sym_LBRACE_LBRACE,
  [283] = 2,
    ACTIONS(55), 1,
      sym_literal_text,
    ACTIONS(57), 1,
      anon_sym_LBRACE_LBRACE,
  [290] = 2,
    ACTIONS(76), 1,
      sym_literal_text,
    ACTIONS(78), 1,
      anon_sym_LBRACE_LBRACE,
  [297] = 2,
    ACTIONS(88), 1,
      sym_literal_text,
    ACTIONS(90), 1,
      anon_sym_LBRACE_LBRACE,
  [304] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [308] = 1,
    ACTIONS(110), 1,
      anon_sym_RBRACE_RBRACE,
  [312] = 1,
    ACTIONS(112), 1,
      anon_sym_RBRACE_RBRACE,
  [316] = 1,
    ACTIONS(114), 1,
      anon_sym_RBRACE_RBRACE,
  [320] = 1,
    ACTIONS(116), 1,
      sym_identifier,
  [324] = 1,
    ACTIONS(118), 1,
      anon_sym_RBRACE_RBRACE,
  [328] = 1,
    ACTIONS(120), 1,
      anon_sym_RBRACE_RBRACE,
  [332] = 1,
    ACTIONS(122), 1,
      anon_sym_RBRACE_RBRACE,
  [336] = 1,
    ACTIONS(124), 1,
      anon_sym_RBRACE_RBRACE,
  [340] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [344] = 1,
    ACTIONS(128), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 24,
  [SMALL_STATE(18)] = 47,
  [SMALL_STATE(19)] = 70,
  [SMALL_STATE(20)] = 90,
  [SMALL_STATE(21)] = 110,
  [SMALL_STATE(22)] = 121,
  [SMALL_STATE(23)] = 132,
  [SMALL_STATE(24)] = 143,
  [SMALL_STATE(25)] = 151,
  [SMALL_STATE(26)] = 159,
  [SMALL_STATE(27)] = 169,
  [SMALL_STATE(28)] = 179,
  [SMALL_STATE(29)] = 187,
  [SMALL_STATE(30)] = 195,
  [SMALL_STATE(31)] = 203,
  [SMALL_STATE(32)] = 211,
  [SMALL_STATE(33)] = 219,
  [SMALL_STATE(34)] = 227,
  [SMALL_STATE(35)] = 234,
  [SMALL_STATE(36)] = 241,
  [SMALL_STATE(37)] = 248,
  [SMALL_STATE(38)] = 255,
  [SMALL_STATE(39)] = 262,
  [SMALL_STATE(40)] = 269,
  [SMALL_STATE(41)] = 276,
  [SMALL_STATE(42)] = 283,
  [SMALL_STATE(43)] = 290,
  [SMALL_STATE(44)] = 297,
  [SMALL_STATE(45)] = 304,
  [SMALL_STATE(46)] = 308,
  [SMALL_STATE(47)] = 312,
  [SMALL_STATE(48)] = 316,
  [SMALL_STATE(49)] = 320,
  [SMALL_STATE(50)] = 324,
  [SMALL_STATE(51)] = 328,
  [SMALL_STATE(52)] = 332,
  [SMALL_STATE(53)] = 336,
  [SMALL_STATE(54)] = 340,
  [SMALL_STATE(55)] = 344,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_helper_call_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_helper_call_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_helper_call, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handleblock, 3, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handleblock, 3, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handleblock, 2, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handleblock, 2, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_end, 4, 0, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_end, 4, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__handlebars, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__handlebars, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_start, 4, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_start, 4, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__partial_start, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__partial_start, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__macro_start, 5, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__macro_start, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_handlebars_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
