#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  sym_literal_text = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_RBRACE_RBRACE = 3,
  sym__identifier = 4,
  anon_sym_DOT = 5,
  anon_sym_POUND = 6,
  anon_sym_SLASH = 7,
  anon_sym_STAR = 8,
  anon_sym_GT = 9,
  sym_source_file = 10,
  sym__content = 11,
  sym__handlebars = 12,
  sym__expression = 13,
  sym_context_reference = 14,
  sym_helper_call = 15,
  sym__block_start = 16,
  sym__block_end = 17,
  sym_handleblock = 18,
  sym__macro_start = 19,
  sym_macro = 20,
  sym__partial_start = 21,
  sym_partial = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_context_reference_repeat1 = 24,
  aux_sym_helper_call_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_literal_text] = "literal_text",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym__identifier] = "_identifier",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [anon_sym_SLASH] = "/block",
  [anon_sym_STAR] = "*",
  [anon_sym_GT] = ">",
  [sym_source_file] = "source_file",
  [sym__content] = "_content",
  [sym__handlebars] = "_handlebars",
  [sym__expression] = "_expression",
  [sym_context_reference] = "context_reference",
  [sym_helper_call] = "helper_call",
  [sym__block_start] = "_block_start",
  [sym__block_end] = "_block_end",
  [sym_handleblock] = "handleblock",
  [sym__macro_start] = "_macro_start",
  [sym_macro] = "macro",
  [sym__partial_start] = "_partial_start",
  [sym_partial] = "partial",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_context_reference_repeat1] = "context_reference_repeat1",
  [aux_sym_helper_call_repeat1] = "helper_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_literal_text] = sym_literal_text,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym__identifier] = sym__identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_GT] = anon_sym_GT,
  [sym_source_file] = sym_source_file,
  [sym__content] = sym__content,
  [sym__handlebars] = sym__handlebars,
  [sym__expression] = sym__expression,
  [sym_context_reference] = sym_context_reference,
  [sym_helper_call] = sym_helper_call,
  [sym__block_start] = sym__block_start,
  [sym__block_end] = sym__block_end,
  [sym_handleblock] = sym_handleblock,
  [sym__macro_start] = sym__macro_start,
  [sym_macro] = sym_macro,
  [sym__partial_start] = sym__partial_start,
  [sym_partial] = sym_partial,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_context_reference_repeat1] = aux_sym_context_reference_repeat1,
  [aux_sym_helper_call_repeat1] = aux_sym_helper_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym__handlebars] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_context_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_helper_call] = {
    .visible = true,
    .named = true,
  },
  [sym__block_start] = {
    .visible = false,
    .named = true,
  },
  [sym__block_end] = {
    .visible = false,
    .named = true,
  },
  [sym_handleblock] = {
    .visible = true,
    .named = true,
  },
  [sym__macro_start] = {
    .visible = false,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym__partial_start] = {
    .visible = false,
    .named = true,
  },
  [sym_partial] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_helper_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_helper = 1,
  field_helper = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_helper] = "block_helper",
  [field_helper] = "helper",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_block_helper, 0, .inherited = true},
  [1] =
    {field_helper, 0},
  [2] =
    {field_block_helper, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [0] = anon_sym_SLASH,
    [2] = anon_sym_SLASH,
    [3] = anon_sym_SLASH,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 9,
  [14] = 6,
  [15] = 8,
  [16] = 10,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 36,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 31,
  [45] = 32,
  [46] = 34,
  [47] = 35,
  [48] = 38,
  [49] = 37,
  [50] = 33,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 55,
  [61] = 51,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == '}') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '{') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == '}') ADVANCE(8);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '{') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_literal_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_literal_text);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym__identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(52),
    [sym__content] = STATE(2),
    [sym__handlebars] = STATE(2),
    [sym__block_start] = STATE(4),
    [sym_handleblock] = STATE(2),
    [sym__macro_start] = STATE(5),
    [sym_macro] = STATE(2),
    [sym__partial_start] = STATE(6),
    [sym_partial] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_literal_text] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_literal_text,
    STATE(4), 1,
      sym__block_start,
    STATE(5), 1,
      sym__macro_start,
    STATE(6), 1,
      sym__partial_start,
    STATE(10), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [27] = 7,
    ACTIONS(11), 1,
      sym_literal_text,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(45), 1,
      sym__block_end,
    STATE(13), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [54] = 7,
    ACTIONS(15), 1,
      sym_literal_text,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(31), 1,
      sym__block_end,
    STATE(15), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [81] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(32), 1,
      sym__block_end,
    STATE(9), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [108] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(21), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(34), 1,
      sym__block_end,
    STATE(11), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [135] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(23), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(44), 1,
      sym__block_end,
    STATE(8), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [162] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(48), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [189] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(37), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [216] = 7,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_literal_text,
    ACTIONS(32), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(4), 1,
      sym__block_start,
    STATE(5), 1,
      sym__macro_start,
    STATE(6), 1,
      sym__partial_start,
    STATE(10), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [243] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(33), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [270] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(50), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [297] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(49), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [324] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(35), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(46), 1,
      sym__block_end,
    STATE(12), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [351] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(38), 1,
      sym__block_end,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [378] = 6,
    ACTIONS(37), 1,
      sym_literal_text,
    ACTIONS(40), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(3), 1,
      sym__macro_start,
    STATE(7), 1,
      sym__block_start,
    STATE(14), 1,
      sym__partial_start,
    STATE(16), 6,
      sym__content,
      sym__handlebars,
      sym_handleblock,
      sym_macro,
      sym_partial,
      aux_sym_source_file_repeat1,
  [402] = 6,
    ACTIONS(43), 1,
      sym__identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_SLASH,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(55), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [423] = 6,
    ACTIONS(43), 1,
      sym__identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(53), 1,
      anon_sym_SLASH,
    STATE(55), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [444] = 5,
    ACTIONS(55), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(57), 1,
      sym__identifier,
    ACTIONS(59), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_context_reference_repeat1,
    STATE(23), 4,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
      aux_sym_helper_call_repeat1,
  [463] = 4,
    ACTIONS(59), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_context_reference_repeat1,
    ACTIONS(55), 2,
      anon_sym_RBRACE_RBRACE,
      sym__identifier,
    STATE(24), 4,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
      aux_sym_helper_call_repeat1,
  [480] = 5,
    ACTIONS(43), 1,
      sym__identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(60), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [498] = 5,
    ACTIONS(43), 1,
      sym__identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(55), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [516] = 3,
    ACTIONS(57), 1,
      sym__identifier,
    ACTIONS(61), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(25), 4,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
      aux_sym_helper_call_repeat1,
  [529] = 2,
    ACTIONS(61), 2,
      anon_sym_RBRACE_RBRACE,
      sym__identifier,
    STATE(25), 4,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
      aux_sym_helper_call_repeat1,
  [540] = 3,
    ACTIONS(63), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(65), 1,
      sym__identifier,
    STATE(25), 4,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
      aux_sym_helper_call_repeat1,
  [553] = 2,
    ACTIONS(43), 1,
      sym__identifier,
    STATE(53), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [562] = 2,
    ACTIONS(43), 1,
      sym__identifier,
    STATE(54), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [571] = 3,
    ACTIONS(59), 1,
      anon_sym_DOT,
    STATE(30), 1,
      aux_sym_context_reference_repeat1,
    ACTIONS(68), 2,
      anon_sym_RBRACE_RBRACE,
      sym__identifier,
  [582] = 2,
    ACTIONS(43), 1,
      sym__identifier,
    STATE(58), 3,
      sym__expression,
      sym_context_reference,
      sym_helper_call,
  [591] = 3,
    ACTIONS(72), 1,
      anon_sym_DOT,
    STATE(30), 1,
      aux_sym_context_reference_repeat1,
    ACTIONS(70), 2,
      anon_sym_RBRACE_RBRACE,
      sym__identifier,
  [602] = 2,
    ACTIONS(77), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [610] = 2,
    ACTIONS(81), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [618] = 2,
    ACTIONS(85), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [626] = 2,
    ACTIONS(89), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [634] = 2,
    ACTIONS(93), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [642] = 2,
    ACTIONS(97), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [650] = 2,
    ACTIONS(101), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [658] = 2,
    ACTIONS(105), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_literal_text,
  [666] = 1,
    ACTIONS(70), 3,
      anon_sym_RBRACE_RBRACE,
      sym__identifier,
      anon_sym_DOT,
  [672] = 2,
    ACTIONS(95), 1,
      sym_literal_text,
    ACTIONS(97), 1,
      anon_sym_LBRACE_LBRACE,
  [679] = 2,
    ACTIONS(107), 1,
      sym_literal_text,
    ACTIONS(109), 1,
      anon_sym_LBRACE_LBRACE,
  [686] = 2,
    ACTIONS(111), 1,
      sym_literal_text,
    ACTIONS(113), 1,
      anon_sym_LBRACE_LBRACE,
  [693] = 2,
    ACTIONS(115), 1,
      sym_literal_text,
    ACTIONS(117), 1,
      anon_sym_LBRACE_LBRACE,
  [700] = 2,
    ACTIONS(75), 1,
      sym_literal_text,
    ACTIONS(77), 1,
      anon_sym_LBRACE_LBRACE,
  [707] = 2,
    ACTIONS(79), 1,
      sym_literal_text,
    ACTIONS(81), 1,
      anon_sym_LBRACE_LBRACE,
  [714] = 2,
    ACTIONS(87), 1,
      sym_literal_text,
    ACTIONS(89), 1,
      anon_sym_LBRACE_LBRACE,
  [721] = 2,
    ACTIONS(91), 1,
      sym_literal_text,
    ACTIONS(93), 1,
      anon_sym_LBRACE_LBRACE,
  [728] = 2,
    ACTIONS(103), 1,
      sym_literal_text,
    ACTIONS(105), 1,
      anon_sym_LBRACE_LBRACE,
  [735] = 2,
    ACTIONS(99), 1,
      sym_literal_text,
    ACTIONS(101), 1,
      anon_sym_LBRACE_LBRACE,
  [742] = 2,
    ACTIONS(83), 1,
      sym_literal_text,
    ACTIONS(85), 1,
      anon_sym_LBRACE_LBRACE,
  [749] = 1,
    ACTIONS(119), 1,
      sym__identifier,
  [753] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
  [757] = 1,
    ACTIONS(123), 1,
      anon_sym_RBRACE_RBRACE,
  [761] = 1,
    ACTIONS(125), 1,
      anon_sym_RBRACE_RBRACE,
  [765] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACE_RBRACE,
  [769] = 1,
    ACTIONS(129), 1,
      sym__identifier,
  [773] = 1,
    ACTIONS(131), 1,
      anon_sym_RBRACE_RBRACE,
  [777] = 1,
    ACTIONS(133), 1,
      anon_sym_RBRACE_RBRACE,
  [781] = 1,
    ACTIONS(135), 1,
      anon_sym_RBRACE_RBRACE,
  [785] = 1,
    ACTIONS(137), 1,
      anon_sym_RBRACE_RBRACE,
  [789] = 1,
    ACTIONS(139), 1,
      sym__identifier,
  [793] = 1,
    ACTIONS(141), 1,
      sym__identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 189,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 297,
  [SMALL_STATE(14)] = 324,
  [SMALL_STATE(15)] = 351,
  [SMALL_STATE(16)] = 378,
  [SMALL_STATE(17)] = 402,
  [SMALL_STATE(18)] = 423,
  [SMALL_STATE(19)] = 444,
  [SMALL_STATE(20)] = 463,
  [SMALL_STATE(21)] = 480,
  [SMALL_STATE(22)] = 498,
  [SMALL_STATE(23)] = 516,
  [SMALL_STATE(24)] = 529,
  [SMALL_STATE(25)] = 540,
  [SMALL_STATE(26)] = 553,
  [SMALL_STATE(27)] = 562,
  [SMALL_STATE(28)] = 571,
  [SMALL_STATE(29)] = 582,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 602,
  [SMALL_STATE(32)] = 610,
  [SMALL_STATE(33)] = 618,
  [SMALL_STATE(34)] = 626,
  [SMALL_STATE(35)] = 634,
  [SMALL_STATE(36)] = 642,
  [SMALL_STATE(37)] = 650,
  [SMALL_STATE(38)] = 658,
  [SMALL_STATE(39)] = 666,
  [SMALL_STATE(40)] = 672,
  [SMALL_STATE(41)] = 679,
  [SMALL_STATE(42)] = 686,
  [SMALL_STATE(43)] = 693,
  [SMALL_STATE(44)] = 700,
  [SMALL_STATE(45)] = 707,
  [SMALL_STATE(46)] = 714,
  [SMALL_STATE(47)] = 721,
  [SMALL_STATE(48)] = 728,
  [SMALL_STATE(49)] = 735,
  [SMALL_STATE(50)] = 742,
  [SMALL_STATE(51)] = 749,
  [SMALL_STATE(52)] = 753,
  [SMALL_STATE(53)] = 757,
  [SMALL_STATE(54)] = 761,
  [SMALL_STATE(55)] = 765,
  [SMALL_STATE(56)] = 769,
  [SMALL_STATE(57)] = 773,
  [SMALL_STATE(58)] = 777,
  [SMALL_STATE(59)] = 781,
  [SMALL_STATE(60)] = 785,
  [SMALL_STATE(61)] = 789,
  [SMALL_STATE(62)] = 793,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_reference, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_helper_call, 2, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_helper_call_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_helper_call_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_reference, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_reference_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handleblock, 2, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handleblock, 2, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__handlebars, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__handlebars, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_end, 4, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_end, 4, 0, 4),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handleblock, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handleblock, 3, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_start, 4, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_start, 4, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__partial_start, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__partial_start, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__macro_start, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__macro_start, 5, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_handlebars_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
